name: Tests
on: push
jobs:
  tests:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ['3.12']

    name: Python ${{ matrix.python-version }}

    steps:
    - name: Set up Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox==2023.4.22
        pip install poetry==1.7.1

    - name: Run tests with nox
      run: nox
